version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=redhat
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=chirag

  nextcloudos:
    image: nextcloud
    ports:
      - 8080:80
    links:
      - db
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=chirag
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_HOST=db
    volumes:
      - nextcloud:/var/www/html
    restart: always
